### ISSUE TITLE
Grants listed should not be clickable

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#100]
To reproduce:
- Navigate to https://develop-op-voting.up.railway.app/project/0x04d4b89e72e276bebc4bb4359145bc89e12f64a1edb1d85e97a5aa9c65660da5
- Scroll down to Grants & Investments
- Notice that a cursor and expansion icon appear in the top two grants but they are not actually clickable
![Screenshot 2024-09-17 at 5 50 42 PM](https://github.com/user-attachments/assets/9a8a7070-64cd-4ad1-af06-1169f744ad63)

**Comment by vidvidvid** [comment]
use card instead of accordion if there is no content
