### ISSUE TITLE
Progress bar on the locked ballot page is incorrect

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#102]
The progress bar on the locked ballot page is incorrect and showing 50 projects (when my category only has 9 projects). 

Currently: 
<img width="1219" alt="Screenshot 2024-09-17 at 2 56 58 PM" src="https://github.com/user-attachments/assets/dda842b3-0234-4f73-b32e-2dd72fc88494">

**Comment by vidvidvid** [comment]
- this will get fixed once the api discrepancy gets resolved (nr. of projects to score vs nr. of projects that load)
- these '50' aren't from the same category
