### ISSUE TITLE
Ballot page

### ISSUE THREAD

**Issue by vidvidvid** [grants-stack-frontier/op-rf4-voting-ui#105]
- [x] conflict of interest -> need to be below the ballot allocation
- [x] update allocations (when distrib. method is selected - pending)
- [ ] saving the position (api issue?)
- [x] adding a calculator next to the save button
- [x] change text to `Save budget and ballot`
- [x] update allocation amounts (based on category?)
- [x] some project descriptions aren't rendering (project/to evaluate discrepancy)

**Comment by geovgy** [comment]
For context, 2 and 3 are API issues. Allocations already update on distribution selection (just not properly). Last one will likely be resolved too after updates to the API.
