### ISSUE TITLE
Allocation Method not working

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#123]
On the ballot page, when choosing an allocation method
1. The input on the projects seem to be OP Amounts but need to be percentages 
2. It sometimes takes a long time for the allocation method to apply, maybe we could have a small loading animation in the bottom right corner? 

https://github.com/user-attachments/assets/d9305af8-b5b7-4f0b-a837-34eeab6d1ef5

**Comment by meglister** [comment]
Noting this additional error related to the inputs being wrongly formatted. I think that by default they should sum up to 100%

<img width="1077" alt="Screenshot 2024-09-19 at 9 33 53 AM" src="https://github.com/user-attachments/assets/d29e6962-f1b8-4705-a673-da9fa06631aa">

**Comment by JSeiferth** [comment]
<img width="852" alt="Screenshot 2024-09-19 at 16 02 21" src="https://github.com/user-attachments/assets/bc6971e1-5868-4aa9-8ce7-74055028883a">
This seems to be an API issue

**Comment by geovgy** [comment]
1. My assumption was the allocations would be returned in %s like it is for category allocations. Waiting until some clarity on the API side but will change it if tended to be OP amount and remain that way.
2. Yeah its painfully slow. Making some changes to cut down the time. For the load animation, do you mean have it on the bottom right corner of the whole allocation method section (like above the search bar)?

**Comment by shaunop** [comment]
> Noting this additional error related to the inputs being wrongly formatted. I think that by default they should sum up to 100%
> 
> <img alt="Screenshot 2024-09-19 at 9 33 53 AM" width="1077" src="https://private-user-images.githubusercontent.com/72808678/369014417-d29e6962-f1b8-4705-a673-da9fa06631aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjE2NzIsIm5iZiI6MTcyNjc2MTM3MiwicGF0aCI6Ii83MjgwODY3OC8zNjkwMTQ0MTctZDI5ZTY5NjItZjFiOC00NzA1LWE2NzMtZGE5ZmEwNjYzMWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE1NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NTNkOGZlMjU4OGYxOWE4Yjk5YTU5NDU2OTE1OTQ0NDg2NjE3OGY5YTY3MzBiY2Y5Njg0NjY4ZTg1Y2Q2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VjQ3WlW40t5RfaHapho9Hba8no-GGew2wZ16K3gDRY0">

We decided not to apply the 100% auto-balance feature to the ballot list, thinking it would be slow and cumbersome. The intention is that users start with a preset allocation method, then make changes from there. Users will be responsible for adding their percentages up to 100.

**Comment by shaunop** [comment]
> 2\. Yeah its painfully slow. Making some changes to cut down the time. For the load animation, do you mean have it on the bottom right corner of the whole allocation method section (like above the search bar)?

Could we use a loading **toast-component** in the bottom right? Like this: 

<img width="1144" alt="Screenshot 2024-09-19 at 9 06 52 AM" src="https://github.com/user-attachments/assets/3e77c54b-106b-4357-8304-b8318881b501">

**Comment by JSeiferth** [comment]
<img width="1084" alt="Screenshot 2024-09-20 at 14 40 29" src="https://github.com/user-attachments/assets/8de6c281-a9ba-4b65-aeb8-e8846e7c00d3">
Not sure if this is on the API or frontend, but lets please round numbers up until the second number after comma, e.g. 5.01%

**Comment by meglister** [comment]
think this is fixed, issue mentioned by Jonas is being tracked separately: #160
