### ISSUE TITLE
Submit Ballot: Bad payload

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#124]
When submitting the ballot, I only sign the category allocations but not the project allocations. When signing the ballot, I get a "Error publishing ballot" message

<img width="477" alt="Screenshot 2024-09-19 at 12 12 40" src="https://github.com/user-attachments/assets/b5af648d-7bb0-4d90-a39d-2520ebc92a73">

**Comment by meglister** [comment]
Experienced the same issue

Video (skip past the math part to the end): https://www.loom.com/share/143595f4e8274846a6104ccc9e8b9314

Console error screenshot 
<img width="799" alt="Screenshot 2024-09-19 at 9 51 40 AM" src="https://github.com/user-attachments/assets/ce922602-bc60-4d60-9b3e-846e0d2c2853">

**Comment by geovgy** [comment]
Fixed
