### ISSUE TITLE
Funding: denotations and labeling

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#125]
Go to ["Delta Network Upgrade" Project](https://develop-op-voting.up.railway.app/project/0x41275977def21cc80eaddabfc98c04cf02df9c92c918070437d9619a8151b9f5), scroll down to Grants & Investments. 

1. **The "Investment" category should be denoted in dollars ($) not in OP, see screenshot below of app and data and designs**
<img width="802" alt="Screenshot 2024-09-19 at 12 22 11" src="https://github.com/user-attachments/assets/b89c82c0-d67a-43e7-a099-67e91108d800">
<img width="660" alt="Screenshot 2024-09-19 at 12 22 27" src="https://github.com/user-attachments/assets/410fab3b-6990-45b0-9686-1ca355325f8a">
<img width="827" alt="Screenshot 2024-09-19 at 12 25 26" src="https://github.com/user-attachments/assets/3795e12b-585f-42bc-b924-ba3f530c9b5f">

**2. Retro Funding is missing a "Retro Funding" label and round label. See screenshot of app where there's just a number and an OP amount, also attached screenshot of data and designs**
<img width="758" alt="Screenshot 2024-09-19 at 12 24 11" src="https://github.com/user-attachments/assets/ce2e0831-c8e6-445f-a31b-d3d558d317cb">

<img width="730" alt="Screenshot 2024-09-19 at 12 24 22" src="https://github.com/user-attachments/assets/adb62fc0-ad6c-4d76-8b92-899b6294ed4d">

<img width="709" alt="Screenshot 2024-09-19 at 12 24 33" src="https://github.com/user-attachments/assets/3842daff-abb5-484b-8387-d8c70791d015">

**Comment by emadellaloggia** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by nitegeist** [comment]
I'm not sure if we're viewing the same project here but the data I'm seeing is far more scarce than the objects you're showing here. I'll ask Stepan about it. 
![image](https://github.com/user-attachments/assets/441e4f67-2963-440b-b869-ec4c6151a614)
****

**Comment by nitegeist** [comment]
This one is sort of ongoing as this `funding` prop doesn't exist for me currently

**Comment by JSeiferth** [comment]
<img width="791" alt="Screenshot 2024-09-25 at 11 54 02" src="https://github.com/user-attachments/assets/a55444ba-81bf-40b5-97c8-e1ed59acf863">
Could we add the Retro Funding round here? e.g. Retro Funding 3, instead of just Retro Funding? @nitegeist

**Comment by vidvidvid** [comment]
@JSeiferth can you pls link the project where you saw this?

**Comment by JSeiferth** [comment]
Here's an example @vidvidvid https://round5.optimism.io/project/0x8d73a6f4342f92358b4a46e90336ce2e858d844fc78d3ca5d46f94ac09757918

**Comment by JSeiferth** [comment]
@vidvidvid this still seems to be an issue, see [here](https://develop-op-voting.up.railway.app/project/0x078cf11f1d64911d10f1d57c1da9c09d67a167472afc530f3412c304ee0f239e)

It should have round notation, e.g. "Retro Funding 3", "Retro Funding 4", etc.

**Comment by JSeiferth** [comment]
Oh, seems like the API is not returning this 
<img width="722" alt="Screenshot 2024-09-27 at 10 19 13" src="https://github.com/user-attachments/assets/bd1f8e19-170a-4c77-9c51-e95fb9edc6ce">


but it's in the data that we have 
<img width="488" alt="Screenshot 2024-09-27 at 10 19 27" src="https://github.com/user-attachments/assets/68435a10-5ab1-4b4d-9ccc-249988922162">

**Comment by vidvidvid** [comment]
closing in favour of https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/252
