### ISSUE TITLE
Picture missing: "One-click bare metal node deployment"

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#126]
Go to ["One-click bare metal node deployment" Project
](https://develop-op-voting.up.railway.app/project/0xcf7477b956b4001b44a618139890f8decf0ad34ae55f0db1f01789040a17af0c)

See profile pics not loading
<img width="778" alt="Screenshot 2024-09-19 at 12 39 46" src="https://github.com/user-attachments/assets/efe832eb-cfe0-46ba-9289-a11304a77610">

**Comment by Andrez092** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by nitegeist** [comment]
Currently seeing both the profile picture and org picture on develop. It could be that the images take a while to get returned from `storage.googleapis.com` I'll add the `priority` attribute to the images and see if that helps
![image](https://github.com/user-attachments/assets/87d276d4-09f5-4727-900d-5945027c4338)

**Comment by JSeiferth** [comment]
<img width="822" alt="Screenshot 2024-09-20 at 14 25 43" src="https://github.com/user-attachments/assets/147e2e8d-d0d3-4753-8ee1-cfd44dcbfecf">
Still missing a picture from time to time @nitegeist

**Comment by JSeiferth** [comment]
Still encountering the same issue
<img width="1505" alt="Screenshot 2024-09-25 at 12 24 56" src="https://github.com/user-attachments/assets/6fab5340-d85f-4f56-abab-d1de216b622f">
