### ISSUE TITLE
Project Rating: Skipping project results in endless loop

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#127]
When rating projects, I clicked skip on 2. Now I can't rate them anymore and can't proceed to the ballot. 

The expected behavior is that 
1. I can edit my rating 
2. I will be shown the projects I skipped at the end (e.g. If project A is first in line and skipped, it is sorted to be last in line)

<img width="1130" alt="Screenshot 2024-09-19 at 12 44 37" src="https://github.com/user-attachments/assets/a291e0f6-785a-467c-8a8e-d1a24e23ca13">

**Comment by KERERCVASD** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by meglister** [comment]
Adding a video here to reproduce this behavior -- ignore my voiceover, I thought it was triggered by advancing while the impact score was still being saved, but I realized Jonas' analysis re skipped projects is correct!

https://www.loom.com/share/3c6ff47c35be4d16a6a86f17c31dd37e?sid=af6f86f7-85e8-4baf-b992-005cff3fb63f

Steps to reproduce:
1. Open ballot and rate some projects, skip some other projects
2. After completing your ratings, notice that you are stuck in a loop where skipped projects are continually displayed but not able to be edited
3. Notice that you are not able to advance to the ballot stage

Related to #72

**Comment by meglister** [comment]
Also noting that when I manually went to my ballot to get out of this loop, there are 39 projects with scores appearing -- so somehow the skipped projects were assigned a score. Wonder if I'm triggering a weird state w all the testing over the last few days?

**Comment by JSeiferth** [comment]
> Also noting that when I manually went to my ballot to get out of this loop, there are 39 projects with scores appearing -- so somehow the skipped projects were assigned a score. Wonder if I'm triggering a weird state w all the testing over the last few days?

Experienced the same thing 👍
