### ISSUE TITLE
Total ballot allocation does not update until page is refreshed

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#130]
Overview: the calculation of total % allocated does not refresh until the page is manually reloaded. This means that if a user adjusts their percentages from <100% to 100%, they need to manually refresh the page before submitting

Steps to repro:
1. Open ballot page
2. Input % not equal to 100%
3. Observe warning error and disabled submit button at bottom of page
4. Adjust to 100%
5. Notice that warning error/submit button are still present
6. Reload page and notice that error is gone, submit button is enabled

Video: (sorry the end is a diff bug) 
https://www.loom.com/share/143595f4e8274846a6104ccc9e8b9314?sid=c7c2a92c-1a80-486c-a4c3-a87e79181844

**Comment by meglister** [comment]
This is a dupe of #129

**Comment by vidvidvid** [comment]
https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/129

**Comment by meglister** [comment]
Think we can close this, observed it is fixed! cc @geovgy
