### ISSUE TITLE
Project Page: Repo Metrics missing

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#131]
When untoggling the Github repo link, you don't see metrics. See [this project](https://develop-op-voting.up.railway.app/project/0x29689510e5add50d929566fcbb78a8f85fac28545928859f97ce6c5ca3c97da1) as an example
<img width="760" alt="Screenshot 2024-09-19 at 15 57 04" src="https://github.com/user-attachments/assets/7e85ef8e-1bb7-4b52-a6c6-aee0176b25e4">

See designs of the repo metrics [here](https://www.figma.com/design/1j0mOMlZWtve4GK5kF0WQU/Voting?node-id=6882-65719&t=9TSOfku9WJ4iY8Uo-4)
<img width="581" alt="Screenshot 2024-09-19 at 15 57 58" src="https://github.com/user-attachments/assets/7d1f9175-957e-4ce8-8a1b-353f770cfd09">

**Comment by nitegeist** [comment]
Will escalate to Stepan
