### ISSUE TITLE
Grants and investments should show more data

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#135]
Project detail view: 

Investigate — Grants and investments should show more data. In the application, some options should contain a type, link, year/round, amount, and details. 

Current:
<img width="750" alt="Screenshot 2024-09-19 at 9 33 26 AM" src="https://github.com/user-attachments/assets/f2c8f0c1-85f7-4a81-83c9-203edf51ffb2">

Design:
<img width="768" alt="Screenshot 2024-09-19 at 9 35 54 AM" src="https://github.com/user-attachments/assets/b29a75fe-7d01-4556-b039-c8758c008a13">

**Comment by nitegeist** [comment]
I'll raise this issue escalate this issue to Stepan as I can only display what I receive from the API

**Comment by nitegeist** [comment]
#125 is related to this as well

**Comment by vidvidvid** [comment]
made a more robust solution that should handle all the cases and properly display all the info of every type of grants/investments. please check @shaunop
