### ISSUE TITLE
Pricing information missing

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#147]
On [Sherlock project](https://develop-op-voting.up.railway.app/project/0xc8a03780dc632e8fad9356662e52723f5e6cff9ba457c0f29e15653c2d26fe7c) the pricing information is missing when untoggling. 
<img width="749" alt="Screenshot 2024-09-20 at 15 17 57" src="https://github.com/user-attachments/assets/cc56c34c-dd58-4f48-bbbb-21c6beb931f9">

See a screenshot of the data that should be displayed
<img width="977" alt="Screenshot 2024-09-20 at 15 18 22" src="https://github.com/user-attachments/assets/0dcf3eec-9f41-4a14-b897-e73872355a88">

**Comment by nitegeist** [comment]
@JSeiferth I'm starting to wonder if we're using the same api because I'm not seeing `pricingModelDetails` in the data that is returned to me even when I go to the develop url😕 
![image](https://github.com/user-attachments/assets/071ea30b-b5ff-4a96-950b-2f27bbe2595f)
