### ISSUE TITLE
Update info box on budgeting page

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#148]
Here is the correct copy, please see Figma for styling: https://www.figma.com/design/1j0mOMlZWtve4GK5kF0WQU/Voting?node-id=8021-77801&node-type=frame&t=K5yhC1xaeLfNFWOS-0

--

The Optimism Foundation initially set the Round 5 budget to 8M OP. They decided on this budget after reviewing the results from Round 3—where 40+ OP Stack projects were allocated 6.5M+ OP by voters.

Estimating that the impact within the OP Stack category has increased since round 3, the Foundation set a higher budget of 8M OP.

However, less projects have qualified for the round than expected. In total, there are {number} eligible projects.

Additional context

To help you determine a Round 5 budget, it’s useful to reference existing data on Optimism allocations towards grants:

Retro Funding 4 allocated 10M OP among 207 Onchain builders for driving the adoption of Optimism
The Token House has allocated 1M OP+ since Jan 2023 to 20+ proactive grants for OP Stack contributions
The Foundation has issued a 250k OP grant to build Zero Knowledge proofs for the OP Stack

Responsible allocation of OP enables the Collective to fund more builders, and to sustainably pursue Retro Funding into the future. Any unallocated OP will be used to reward impact in future rounds.

**Comment by shaunop** [comment]
> Group Discussion
> 
> The Foundation will hold a group call for voters on {September 20 at 10 AM UTC} to discuss budgeting. You’ll receive an email invitation.

@meglister can you remove this last part please?

**Comment by meglister** [comment]
done, thanks @shaunop !

**Comment by shaunop** [comment]
Hey there, we have some small changes after legal review to the bottom half of this content. @vidvidvid 

Under "Additional context"...

> To help you determine a Round 5 budget, it’s useful to reference existing data on Optimism grant allocations:
> 
> Retro Funding 4 allocated 10M OP among 207 Onchain builders for driving the adoption of Optimism
> The Token House has allocated 1M+ OP since Jan 2023 to 20+ proactive grants for OP Stack contributions
> The Foundation has made a 250k OP grant to build Zero Knowledge proofs for the OP Stack
> 
> Responsible allocation of OP enables the Collective to support more builders, and to sustainably pursue Retro Funding into the future. Any unallocated OP will be used to reward impact in future rounds.
