### ISSUE TITLE
Add the ability to reset ballot

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#152]
After testing, we realized that a "reset ballot" feature would be very useful. If there's bandwidth, let's add...

1. Reset button
2. Confirmation modal

Ballot has been edited, show reset button:
![reset_1](https://github.com/user-attachments/assets/c89b326c-8820-4087-beb9-bfa89659fe54)

After clicking button, user confirms ballot reset:
![reset_2](https://github.com/user-attachments/assets/febd7e94-1b66-45cc-a78c-f939b3f777fe)

Ballot is reset:
![reset_3](https://github.com/user-attachments/assets/80faa974-d635-4a35-a942-5d0af132a141)

**Comment by meglister** [comment]
Hey team -- wanted to note that this should come after all of the existing bug fixes
