### ISSUE TITLE
Pre-submit questionnaire changes

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#153]
Hey team, we have changes for the pre-submission questionnaire. 

1. We're removing what were previously questions 3 and 6. 
2. We're adding a new question about the use of "grants and investment" info. 

See below **[and in Figma](https://www.figma.com/design/1j0mOMlZWtve4GK5kF0WQU?node-id=6837-160764#957667459)**:
![questionaire setup](https://github.com/user-attachments/assets/010c49bd-90b2-4b35-ac04-08566f67e3db)
![question 1](https://github.com/user-attachments/assets/36d37b9e-5a89-4806-9cdf-5a51151cc372)
![question 2a](https://github.com/user-attachments/assets/48f2487d-5fd3-47be-9f48-718df3b9abfe)
![question 2b](https://github.com/user-attachments/assets/7162285e-209d-4e6f-b7be-e93e5d234294)
![question 3a](https://github.com/user-attachments/assets/5ef378e1-ed3a-41ed-a8fb-a0f29b85d335)
![question 3b](https://github.com/user-attachments/assets/d54f754b-d9cb-4497-9083-7f3c24079530)
![question 4a](https://github.com/user-attachments/assets/e64eecb4-a5b9-4b73-be83-eb93787d8708)
![question 4b](https://github.com/user-attachments/assets/bb58f13c-f6d0-40b2-9a46-b88ead93e253)
![question 5a](https://github.com/user-attachments/assets/94812455-15b2-43f7-b29c-218a290c7632)
![question 5b](https://github.com/user-attachments/assets/326fec46-1284-4c46-9589-985547acd18b)
![Submit](https://github.com/user-attachments/assets/3ea1bb94-eca7-4e66-8c6f-5db190c9ff4f)

**Comment by vidvidvid** [comment]
jonas to provide new ids

**Comment by JSeiferth** [comment]
It works! Just tested.
