### ISSUE TITLE
I scored all projects to unlock ballot, but was dropped on locked ballot page

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#155]
I scored all projects to unlock ballot, but was dropped on locked ballot page

<img width="1082" alt="Screenshot 2024-09-20 at 12 25 39 PM" src="https://github.com/user-attachments/assets/d6e9e1be-ecdf-4c95-a0ce-4b68b246d0ca">

**Comment by meglister** [comment]
This happened to me too, but I'm having trouble consistently reproducing. What happened to me:

1. Loaded the app directly, did not go thru welcome flow: https://develop-op-voting.up.railway.app/budget
2. Signed in but got a message at the top of the screen saying i was in demo mode/not a badgeholder
3. submitted my budget and was dropped on this ballot screen

**Comment by vidvidvid** [comment]
@meglister thanks, we're on it

**Comment by vidvidvid** [comment]
@meglister @shaunop please check if this is still happening
