### ISSUE TITLE
Unable to load project pages

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#158]
To reproduce:
- I navigated to the ballot page and clicked on a project that I have previously rated (https://develop-op-voting.up.railway.app/project/0xa36ae760edb91ba8bfcc2b52b664fb4731ec09b78033b1bbec9d83d167d590e8)
- Observe that a blank page loads with an application error message. Screenshot attached including console error

![Screenshot 2024-09-21 at 12 43 25 PM](https://github.com/user-attachments/assets/519a41f5-6c7d-4205-9e6c-4fbfd04a9d79)

**Comment by vidvidvid** [comment]
due to schema discrepancy - they load again!
