### ISSUE TITLE
Ballot page not loading unless manually refreshed

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#159]
To reproduce:
1. Navigate to a project page (mine returns app side error)
2. Click back to go to ballot page
3. Observe that URL changes, but ballot page does not appear until manually refreshed

Video: https://www.loom.com/share/36728a2fb1b54e8ab99f7cdb6977c0fc?sid=29798648-8a65-4917-a328-b802a0d40617

**Comment by meglister** [comment]
Still happening for me but only when I navigate back from a project page that will not load

**Comment by vidvidvid** [comment]
@meglister please try this scenario again (hopefully all the client-side errors are now fixed so this shouldn't be possbile)

**Comment by meglister** [comment]
fixed, thanks! @vidvidvid
