### ISSUE TITLE
Round percentages to two decimal points on ballot page

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#160]
To repro:
- Complete project scoring
- Navigate to ballot page: https://develop-op-voting.up.railway.app/ballot
- Apply one of the default allocation methods
- Observe that many decimal places are displayed and overlap the % sign

Fix:
- Round to two decimal places (eg 3.45%) to match figma

![Screenshot 2024-09-21 at 12 49 03 PM](https://github.com/user-attachments/assets/dab3a6a3-152b-4817-af1b-e90fe09e6398)

**Comment by vidvidvid** [comment]
will be fixed on the backend
