### ISSUE TITLE
Can't load project pages

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#167]
Similar issue to yesterday, but console error is a bit different...

to repro:
1. Log in and go to a ballot. I have previously scored all project
2. Click on one of the projects on the ballot list, eg https://develop-op-voting.up.railway.app/project/0xa36ae760edb91ba8bfcc2b52b664fb4731ec09b78033b1bbec9d83d167d590e8
3. Observe page fails to load 
![Screenshot 2024-09-22 at 10 20 15 AM](https://github.com/user-attachments/assets/d1ced768-5946-4d9c-96d0-fe01ba635326)

**Comment by meglister** [comment]
related ticket: #158

**Comment by vidvidvid** [comment]
@meglister should be fixed once the app deploys.
