### ISSUE TITLE
Only show two decimals places on ballot project 

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#181]
Only show two decimals places on ballot project.

Currently:
<img width="1048" alt="Screenshot 2024-09-23 at 11 33 40 AM" src="https://github.com/user-attachments/assets/7d33de42-0920-4c0f-9b48-f5b611062679">

**Comment by geovgy** [comment]
We are waiting on this to be resolved on the API side to avoid possible issues on our side (i.e. selected a distribution method, changed a couple inputs and now 0.0012% over but can't see where in the UI).
