### ISSUE TITLE
In top-to-bottom and top-weighted, users should be able to drag or input # to reorder the list

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#186]
In top-to-bottom and top-weighted, users should be able to drag or input # to reorder the list. Currently the list-order-input and drag button looks disabled. 

- If user changes the order of the list, then the OP amount for that project should change to reflect it's position in the list (respecting the allocation method). 
- If user manually changes OP amount of any project, then the list converts to the "custom" allocation method. 

Current: 
<img width="1087" alt="Screenshot 2024-09-23 at 11 54 06 AM" src="https://github.com/user-attachments/assets/eb5f9a9b-23a0-4db2-abc4-6142580a7c87">

Design:
<img width="738" alt="Screenshot 2024-09-23 at 11 54 36 AM" src="https://github.com/user-attachments/assets/f5eb110b-ec2d-4be0-83ba-ec17003baed7">

**Comment by geovgy** [comment]
@vidvidvid most of the functionality requested in this issue is already incorporated in PR #202. It overlaps with a couple of the other issues. I suggest merging that PR first and then all that's left should be "input # to reorder the list".

**Comment by vidvidvid** [comment]
@geovgy i have implemented the functionality to change the order via input. please sort out the rebalancing part, because i don't have enough context on how it should behave.

**Comment by geovgy** [comment]
It was mainly an async issue. Just merged a PR to fix it. @shaunop this should work now.
