### ISSUE TITLE
Unlocking an input on the budget step should return that input to the non-locked pool (to be auto-balanced)

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#194]
Unlocking an input on the budget step should return that input to the non-locked pool. So, in the example below, unlocking the 41% input should have returned it to the non-locked pool, and the bottom two input should be 25% each (25 + 25 + 50 = 100)

Current:
https://github.com/user-attachments/assets/e84967dc-66b6-4ba0-8554-040a94a7ccf9

**Comment by vidvidvid** [comment]
@shaunop if i understand you correctly, this is the flow of events you expect:
state 1:
```
input 1: 50
input 2: 40
input 3: 10
```
action: `unlock input 2`
state 2:
```
input 1: 50
input 2: 25
input 3: 25
```
if that's the case, then the backend will have to do the necessary changes, because its current behaviour is different.

**Comment by vidvidvid** [comment]
@shaunop

**Comment by shaunop** [comment]
To clarify: 

LOCKED input 1: 50
LOCKED input 2: 40
UNLOCKED input 3: 10

Action: Unlock input 2

LOCKED input 1: 50
UNLOCKED input 2: 25
UNLOCKED input 3: 25

That's how it worked in Round 4 to my knowledge.

**Comment by vidvidvid** [comment]
@shaunop that's not how it works now. i'll fix a patch on the frontend to also update the %.
