### ISSUE TITLE
Skipped project - stuck on scoring

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#205]
When you previously hit "Skip" on one or multiple projects, you will not be redirected to rate these projects after having rated everything. E.g. I skipped 2 projects, not I rated project 56 out of 58 and I'm stuck and can't proceed to the next project. 
To get around this, I have to navigate back to the ballot, click "rate projects" to get shown project 57/58. To get to project 58 I have to do the same thing again. 

To repro:
1. Rate projects
2. Skip a project
3. See that you're unable to proceed after having rated all projects (that you haven't skipped) 

https://github.com/user-attachments/assets/c85c4960-5f56-4427-89b3-bdecb1d8239b

**Comment by vidvidvid** [comment]
@JSeiferth pushed a fix which should resolve this issue. please test it and let me know if anything is still broken
