### ISSUE TITLE
Ballot: Should not be able to submit negative values

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#208]
I'm able to assign a negative allocation to projects and submit my ballot that way. It should not be possible to have negative allocations. 
<img width="1082" alt="Screenshot 2024-09-25 at 12 09 56" src="https://github.com/user-attachments/assets/f7608214-0c90-4cf3-8c8b-f89eb95d02b7">

**Comment by vidvidvid** [comment]
pending solution in an already opened pr - https://github.com/grants-stack-frontier/op-rf4-voting-ui/pull/213
it also sets the max value to 100
