### ISSUE TITLE
Unlocking Ballot: Refresh required

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#210]
After scoring all project and labelling one project as a COI, clicking on "unlock ballot" I get send back to the ballot but am shown the "Score projects to unlock your ballot" screen. After I refresh this page my ballot is unlocked
<img width="1139" alt="Screenshot 2024-09-25 at 12 33 15" src="https://github.com/user-attachments/assets/ffe4b17e-1d99-49a8-a0c3-ba7fec15e901">

**Comment by vidvidvid** [comment]
@JSeiferth i think this should have been solved by one of my recent prs, can you please check?

**Comment by JSeiferth** [comment]
<img width="1512" alt="Screenshot 2024-09-27 at 19 24 59" src="https://github.com/user-attachments/assets/64c8a839-a33c-45e2-a46f-26c64129726c">

@vidvidvid experiencing the problem that after scoring all projects, I do not get the prompt to unlock ballot
