### ISSUE TITLE
Ballot submission: Payload does not include category allocation

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#212]
When submitting my ballot, the category allocation was not included in the payload. 
To reproduce, do not edit or change anything on the budget page and submit your ballot. (e.g. I just went ahead and skipped this page, scored projects and submitted my ballot). 

Expected behavior: Record category allocations and budget, even if they have not been changed from the defaults. Or, require user to change them 

`{"budget":[4600000](tel:4600000),"category_allocation":[],"projects_allocation":[{"project_id":"0x41275977def21cc80eaddabfc98c04cf02df9c92c918070437d9619a8151b9f5","allocation":"5.102040816326531","impact":5},`

**Comment by meglister** [comment]
Adding notes:
- This issue occurs ONLY when the user does not customize the budget allocations and submits the ballot with DEFAULT budget allocations

**Comment by JSeiferth** [comment]
On this issue: Could we force voters to edit the category allocation and budget allocation before submitting their ballot? This way we 
1. Make sure they have considered it and haven't missed it
2. Automagically solve this problem


How this would work is to just show an error message and a disabled submit ballot button

**Comment by vidvidvid** [comment]
@JSeiferth definitely, nice proposition. @geovgy can you wrap this up?

**Comment by vidvidvid** [comment]
https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/256 will also be solved if we do this.

**Comment by geovgy** [comment]
Yep, on it 🫡 Thanks for the suggestion @JSeiferth
