### ISSUE TITLE
Project Page: Support Markdown in project description

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#214]
See [Protocol Guild project page](https://develop-op-voting.up.railway.app/project/0x3e6e0104e18f3c083a8209cbea0b2b36f51d38fd72e71604eb57d757581998e3). It would be nice to support Markdown (or at least line breaks) in the project description
<img width="724" alt="Screenshot 2024-09-25 at 16 33 09" src="https://github.com/user-attachments/assets/04659f9a-62d3-47d0-b97e-3f2117597ffb">

**Comment by vidvidvid** [comment]
@JSeiferth appending the `view more` to the last line (instead of to the bottom) was surprisingly difficult to implement - combining this with markdown will take even more of valuable time. i suggest we move the `view more` below the text for simplicity.

@shaunop opinion, please?

**Comment by shaunop** [comment]
Agree that supporting markdown and breakpoints is important for readability. If you can't get it to work with the appended ...view more, then yes we can place "View more >" below the truncated text. Space the "View more >" just 8pt from the truncated text container to keep it tight. See image:

<img width="725" alt="Screenshot 2024-09-26 at 8 40 21 AM" src="https://github.com/user-attachments/assets/0447fe09-1aa2-482a-a579-29004930c5b1">
