### ISSUE TITLE
Budget Page: Smol copy update

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#215]
On the budget page, below "First, choose how much OP should be dedicated to this round*", it should say "Round 5 rewards impact made to the OP Stack from Oct 2023 - Aug 2024" instead of "Oct 2023 - Oct 2024"

<img width="740" alt="Screenshot 2024-09-25 at 17 01 33" src="https://github.com/user-attachments/assets/53d56b50-6125-4d83-be2f-d6f67e2ca8f6">

**Comment by JSeiferth** [comment]
<img width="789" alt="Screenshot 2024-09-26 at 19 05 56" src="https://github.com/user-attachments/assets/a116119d-6885-4aea-9665-9efa1e078869">
@vidvidvid I still see the same copy as before

**Comment by vidvidvid** [comment]
@JSeiferth the develop branch didn't build due to some linting error that i didn't notice. should be fixed now!
