### ISSUE TITLE
Even if I've unlocked my ballot, I should be able to revisit project detail views

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#219]
Even if I've unlocked my ballot, I should be able to revisit  project detail views. Currently, if I try to revisit a project detail view, I see the unlock ballot modal and then am landed back in the ballot page. 

Current:
https://github.com/user-attachments/assets/88ec21ce-6714-49ff-a245-2e2a6af8b50b

**Comment by nitegeist** [comment]
Duplicate of #206. I'm on it
