### ISSUE TITLE
Retro Funding 5 Voting App

### ISSUE THREAD

**Issue by opjulian** [grants-stack-frontier/op-rf4-voting-ui#220]
### What was the URL where the error occurred?

https://round5.optimism.io/project/0xe4ad25cfe18eccc531582634d03b78b03b7115d5fc77de001e735fe178f768f3

### What happened?

This may be because I am in demo mode, but I get the feedback "Error saving impact score" whenever I try to grade a project 
<img width="1228" alt="Screenshot 2024-09-25 at 6 01 21 PM" src="https://github.com/user-attachments/assets/e323e428-79b9-46a5-bf8f-4afefac7dc6d">

### What should have happened instead?

I believe I should be able to submit an impact score and move on to the next project

### Steps to Reproduce

1. https://round5.optimism.io/budget
2. https://round5.optimism.io/ballot
3. https://round5.optimism.io/project/0xe4ad25cfe18eccc531582634d03b78b03b7115d5fc77de001e735fe178f768f3

### What browser(s) are you seeing the problem on?

Chrome

**Comment by nitegeist** [comment]
This was resolved following a recent api update
