### ISSUE TITLE
alert 'error saving impact score'

### ISSUE THREAD

**Issue by fujianggara10** [grants-stack-frontier/op-rf4-voting-ui#221]
### What was the URL where the error occurred?

https://round5.optimism.io/project/

### What happened?

I would like to report a bug I encountered while voting on the Round 5 Optimism site (https://round5.optimism.io/project/). When I attempted to score a project in the "Ethereum Core Contributions" category, specifically in the section "How would you score this project's impact on the OP Stack?", I received an "error saving impact score" alert each time I selected a scoring option.

After the alert appeared, the page automatically redirected me to another project. However, when I tried to vote on the next project, the same issue occurred, and I once again received the "error saving impact score" message, preventing me from saving my vote.

As a result, I am unable to complete the voting process properly and get stuck in the same cycle for each project.

### What should have happened instead?

After selecting a score in the "How would you score this project's impact on the OP Stack?" section, the system should have successfully saved my score without any error. Upon saving, I expected to receive a confirmation or visual indication that the vote was recorded correctly and then proceed to the next project seamlessly. There should have been no redirection or error messages, allowing for smooth and uninterrupted voting across all projects.
![opstack3](https://github.com/user-attachments/assets/52ee63d9-1322-4a39-a077-905f264b63b0)
![opstack2](https://github.com/user-attachments/assets/1f95ad6a-c663-48ba-a91f-8e0431ed3ae0)
![opstack1](https://github.com/user-attachments/assets/fbd7bbbb-5053-48a8-b593-4198acac1b77)

### Steps to Reproduce

Go to the Round 5 Optimism website at https://round5.optimism.io/project/
Navigate to the Ethereum Core Contributions category
In the section "How would you score this project's impact on the OP Stack?", attempt to select any of the available options
Observe the error message "error saving impact score" that appears after selecting an option
Notice that after the error message, you are automatically redirected to another project
Repeat the voting process on the next project, where the same error occurs, preventing the score from being saved

### Relevant log output

```shell
Page URL: https://round5.optimism.io/project/

Steps:
1. User selects an option in the "How would you score this project's impact on the OP Stack?" section
2. System attempts to save the score
3. Error message "error saving impact score" is displayed
4. User is redirected to the next project automatically
```

**Comment by nitegeist** [comment]
This was resolved following a recent api update
