### ISSUE TITLE
error saving impact score

### ISSUE THREAD

**Issue by joohhnnn** [grants-stack-frontier/op-rf4-voting-ui#229]
### What was the URL where the error occurred?

https://round5.optimism.io/project/0x5960585d5dd67b7778d390be4b8fce7da98d5f056efd2c892e340faebb1d7bc6

### What happened?

![image](https://github.com/user-attachments/assets/88f5a122-331c-480c-9033-b52404aa9fe7)

### What should have happened instead?

saving successfully

### Steps to Reproduce

When I first started selecting projects, I had to choose from over 40 options. I stopped temporarily after making 21 selections, but now the page only requires 20 selections. However, I'm currently unable to proceed with selecting the next project

### Relevant log output

```shell
POST https://round5.optimism.io/api/agora/retrofunding/rounds/5/ballots/0xf8E30C251AA7974aA0A2d9e452d863681f8B59Ac/projects/0x5960585d5dd67b7778d390be4b8fce7da98d5f056efd2c892e340faebb1d7bc6/impact/3 500 (Internal Server Error)
```

**Comment by nitegeist** [comment]
This was resolved following a recent api update
