### ISSUE TITLE
Project redirect stops working

### ISSUE THREAD

**Issue by cheeky-gorilla** [grants-stack-frontier/op-rf4-voting-ui#234]
### What was the URL where the error occurred?

round5.optimism.io/project/<project>

### What happened?

When you score a project, you're meant to be redirected to the next project. That stopped working as I was testing. 

### What should have happened instead?

Should always redirect me to next project after entering vote

### Steps to Reproduce

When viewing a project, go back to Ballot > Budget, then adjust the % allocation per category and total budget, and then go back to reviewing projects. Wont redirect anymore. Only way to fix was to clear cache.  Was able to reproduce this 3 times in Firefox.

### What browser(s) are you seeing the problem on?

Firefox

**Comment by vidvidvid** [comment]
@cheeky-gorilla thank you for the reports. most of these issues should already be resolved - we have been fixing them on the `develop` branch. i just merged it into the `main` branch, which will get deployed to the url where you have been testing the app. i kindly ask you to check your issues again and close out all that don't appear anymore. the deployment should finish in about 10 minutes.

**Comment by cheeky-gorilla** [comment]
> @cheeky-gorilla thank you for the reports. most of these issues should already be resolved - we have been fixing them on the `develop` branch. i just merged it into the `main` branch, which will get deployed to the url where you have been testing the app. i kindly ask you to check your issues again and close out all that don't appear anymore. the deployment should finish in about 10 minutes.

Can you reset my application (if you havent already), so i can test everything from scratch?

**Comment by vidvidvid** [comment]
@cheeky-gorilla can you give me the address you're logged in with so we can reset your data? you can add me on discord if you don't wanna post it here. `vid._`

**Comment by cheeky-gorilla** [comment]
> @cheeky-gorilla can you give me the address you're logged in with so we can reset your data? you can add me on discord if you don't wanna post it here. `vid._`

Fyi while my submission was reset (i.e. I can submit again), all the other inputs have remained, so I cant go through the process of voting on all projects again (as they've already been voted on). If you reset *all* the data I can do so!

**Comment by vidvidvid** [comment]
@cheeky-gorilla i just got a message from the backend dev that he'd prefer not to clear all the data. he'll reset all the ballots on Monday EOD. i'll close this issue until then. 
if you want to test the fresh flow, please simply use another wallet! :)
