### ISSUE TITLE
Not realizing category allocation is 0% 

### ISSUE THREAD

**Issue by cheeky-gorilla** [grants-stack-frontier/op-rf4-voting-ui#235]
### What was the URL where the error occurred?

/ballot

### What happened?

if you set a category allocation to 0%, it'll still ask you to complete your assessment for that category and allocate rewards, with an incorrect # of OP.

### What should have happened instead?

Either skip having to assess / allocate to that category, or when allocating, realize it's 0 OP

### Steps to Reproduce

Set category allocation to 0%, then proceed as normal

### What browser(s) are you seeing the problem on?

Firefox

**Comment by vidvidvid** [comment]
reference https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/180
