### ISSUE TITLE
"add X% to your ballot" is wrong

### ISSUE THREAD

**Issue by cheeky-gorilla** [grants-stack-frontier/op-rf4-voting-ui#237]
### What was the URL where the error occurred?

/ballot

### What happened?

In ballot page, choose "Impact Groups", then go to bottom most project and change to 0. In my case this project had 1.6% before changing to 0. However the notice above the "Submit Ballot and Page' button is telling me to add "2%", 

### What should have happened instead?

Show me correct amount of allocation missing

### Steps to Reproduce

In ballot page, choose "Impact Groups", then go to bottom most project and change to 0. In my case this project had 1.6% before changing to 0. However the notice above the "Submit Ballot and Page' button is telling me to add "2%", 

### What browser(s) are you seeing the problem on?

Firefox

**Comment by vidvidvid** [comment]
right, will fix this!
