### ISSUE TITLE
CSV export only has 1 row

### ISSUE THREAD

**Issue by cheeky-gorilla** [grants-stack-frontier/op-rf4-voting-ui#238]
### What was the URL where the error occurred?

/ballot

### What happened?

Export ballot, open CSV, its one row of data

### What should have happened instead?

One row per project

### Steps to Reproduce

Export ballot, open CSV

### What browser(s) are you seeing the problem on?

Firefox

**Comment by vidvidvid** [comment]
@cheeky-gorilla please check again and let me know if it's fixed now.
use this link to test: https://develop-op-voting.up.railway.app/

**Comment by cheeky-gorilla** [comment]
> @cheeky-gorilla please check again and let me know if it's fixed now. use this link to test: https://develop-op-voting.up.railway.app/

Confirmed fixed via that URL!
