### ISSUE TITLE
Ballot doesnt total 100?

### ISSUE THREAD

**Issue by cheeky-gorilla** [grants-stack-frontier/op-rf4-voting-ui#239]
### What was the URL where the error occurred?

/ballot

### What happened?

This was my budget: 

![Budget](https://github.com/user-attachments/assets/5bd0f352-f37f-4d7a-94f1-7c71f33cbe37)

This was my ballot:
![Ballot](https://github.com/user-attachments/assets/e04f2fc0-d424-480e-ab1d-c1b447eba6f6)

This was the final export of my ballot (once submitted):
[Final Export.csv](https://github.com/user-attachments/files/17159966/Final.Export.csv)

This is the sig of my tx:
{"budget":2900000,"category_allocation":[{"category_slug":"ETHEREUM_CORE_CONTRIBUTIONS","allocation":"99","locked":true},{"category_slug":"OP_STACK_TOOLING","allocation":"1","locked":false},{"category_slug":"OP_STACK_RESEARCH_AND_DEVELOPMENT","allocation":"0","locke	d":true}],"projects_allocation":[{"project_id":"0x417e4e0fab598eee0958d618dfa22dc4ad60eaaa659b811c4780da1df7c7aad6","allocation":"15.06","impact":5},{"project_id":"0xfc00945848ac2ee9a42c64242e90d612cd16435b46082d4a363c087bd7e4c742","allocation":"6.45","impact":4},{"project_id":"0xc150e51f4f208b725e269deb41f71bb6a3ff55633acbfe5b7895dee18609c1ec","allocation":"6.45","impact":4},{"project_id":"0xc6ce7c19e261fb70c69dd6a721637b82fa21a048bf668295487af011c8700186","allocation":"0","impact":4},{"project_id":"0xe4ad25cfe18eccc531582634d03b78b03b7115d5fc77de001e735fe178f768f3","allocation":"4.84","impact":3},{"project_id":"0x907ab6a3f6b6e724797e52051ac04eb23025462f8d06866ee541c90681e0ec17","allocation":"4.84","impact":3},{"project_id":"0x04d4b89e72e276bebc4bb4359145bc89e12f64a1edb1d85e97a5aa9c65660da5","allocation":"4.84","impact":3},{"project_id":"0x29689510e5add50d929566fcbb78a8f85fac28545928859f97ce6c5ca3c97da1","allocation":"4.84","impact":3},{"project_id":"0x3fe005facaaa824b2fd2190be9a1fa124577580dbcdf91f85308725161a79990","allocation":"4.84","impact":3},{"project_id":"0x41275977def21cc80eaddabfc98c04cf02df9c92c918070437d9619a8151b9f5","allocation":"4.84","impact":3},{"project_id":"0xb0acb1a252cdb3b2a7dfadc8c5925da71f005082ec045d8bb3855f64ac4774b9","allocation":"4.84","impact":3},{"project_id":"0xd33479c5420a69c1ce3c8ba955593a63dcd454feeac43a4de417aa0bb793980a","allocation":"3.23","impact":2},{"project_id":"0xc8a03780dc632e8fad9356662e52723f5e6cff9ba457c0f29e15653c2d26fe7c","allocation":"3.23","impact":2},{"project_id":"0xd42d5fa61ac3f9488e7b5c5fd24709d9d2b130750a9e06df868fe0bf3d14b849","allocation":"3.23","impact":2},{"project_id":"0x036fc6760516760a635745917887ae8539ec512f4fde7fd4705a0f3bf3d0cb60","allocation":"3.23","impact":2},{"project_id":"0x6190ca70e5196f582a65d1f73236eff346b72cd922df3305da001bd34c17c348","allocation":"3.23","impact":2},{"project_id":"0xb146c27a51c52f663d11de86f32aca56262b4d23f4502debca1416cdc61b3997","allocation":"3.23","impact":2},{"project_id":"0x7ee54d5d8514a8be9172e4ce0dfb54cc3eba6cf57c88b85e76262dc307178832","allocation":"1.61","impact":1},{"project_id":"0x37df31043d401a09c24ba1066e602ff34c2906ac92397040b5b90694d74eb8d7","allocation":"1.61","impact":1},{"project_id":"0x54d4b15fc19bb1d56a611e650d54847ee6fbc24cc19ed3ecb464a4269268270e","allocation":"1.61","impact":1},{"project_id":"0x64961108e65c1c897e033c5609361839998fbf117c312b211ba7523100c28569","allocation":"1.61","impact":1},{"project_id":"0xb7ab34b29ac7c1f61777caa55b2b0e39de62a3a3f14ca7a48eb26ac6d701d0b2","allocation":"1.61","impact":1},{"project_id":"0xdfeced1045accaf24826bb678bc6c44624588c1d1b5a56d6b60ad2774fde4352","allocation":"1.61","impact":1},{"project_id":"0xd890d5c2369e84688d196a6181ddfde1f1fc9d2d3f4e55ee93a3da851145f96f","allocation":"2.21","impact":1},{"project_id":"0x5a41dd6db9348adfcd8bb0bb0a391a44ac7797094183d536edc8d5677aa985fa","allocation":"2.61","impact":1},{"project_id":"0xbbea5a9a59dc71358d4a4e687630a8a461efc17e56054f36e8c75246520a4199","allocation":"0","impact":1},{"project_id":"0x6605b6f2cb8bad86dd1d82061b0fb7333a6b8d31b9f8c05a2f47cb7d76d0b14f","allocation":"2.21","impact":1},{"project_id":"0x2b5b44d0e98599b5c877792367dcd0ed8f8f849fb267812a936897aa17baa6c4","allocation":"2.21","impact":1},{"project_id":"0x95b0f6f25851da3d3ba17d4cd71e0925b7d234c1db32d5937c846d74ab62fb03","allocation":"0","impact":1}]}

Problems:
- My ballot doesnst add up to 100, right?
- Its showing an incorrect # of OP per project, considering that I put the budget for that category to 0

### What should have happened instead?

- Sum of ballots should equal 100
- I guess, given my budget choice, it should show 0 OP for each project?

### Steps to Reproduce

See screenshots. That was my final choice, however, while reviewing projects I continuously went back and forth adjusting the overall budget. 

### What browser(s) are you seeing the problem on?

Firefox

**Comment by vidvidvid** [comment]
fixed the issue with the OP amount! please check here: https://develop-op-voting.up.railway.app/

sum of ballot is 100.12%. i also fixed the error handling which won't allow the user to submit the ballot in case of a discrepancy like that.
