### ISSUE TITLE
Project Impact Statement missing

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#243]
### What was the URL where the error occurred?

https://develop-op-voting.up.railway.app/project/0xa555f2cc261179e744f961525e3c506a0a53cc02389cb8d59b93c8a9220ed7d7

### What happened?

The Project Impact statement is not displayed

<img width="827" alt="Screenshot 2024-09-27 at 10 02 46" src="https://github.com/user-attachments/assets/c19062f7-ec27-478d-9222-3c3c8cd4924a">

### What should have happened instead?

The impact statement should be displayed

### Steps to Reproduce

1. Go to [Builderism Page](https://develop-op-voting.up.railway.app/project/0xa555f2cc261179e744f961525e3c506a0a53cc02389cb8d59b93c8a9220ed7d7)
2. See that impact statement missing

**Comment by nitegeist** [comment]
This issue was due to the impact statement type changing from 
```ts
{
  answer?: string;
  question?: string;
}
```
to 

```ts
 {
    create: {
      answer?: string;
      question?: string;
    }[];
}
```

I've pushed the fix for this in my latest PR. As soon as it's merged, this will be rectified.
