### ISSUE TITLE
Node Guardians: Github repo metrics missing

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#244]
### What was the URL where the error occurred?

https://develop-op-voting.up.railway.app/project/0x6fc3b802b42153f99ca38a0a5b28f9d675b44aafa6317fddb7e33280b50e8d0a

### What happened?

On [Node Guardian page](https://develop-op-voting.up.railway.app/project/0x6fc3b802b42153f99ca38a0a5b28f9d675b44aafa6317fddb7e33280b50e8d0a), when untoggling the repo, you see the repo metrics return "NaaN"

### What should have happened instead?

Metrics should be displayed

### Steps to Reproduce

1. Head to the [Node Guardian page](https://develop-op-voting.up.railway.app/project/0x6fc3b802b42153f99ca38a0a5b28f9d675b44aafa6317fddb7e33280b50e8d0a)
2. See the Github Repo metrics

**Comment by vidvidvid** [comment]
@JSeiferth in case this happens, should we hide the metric badges?

**Comment by JSeiferth** [comment]
Yes @vidvidvid let's hide the metrics in this case

**Comment by nitegeist** [comment]
@JSeiferth I've done so in my latest PR #254. Once @vidvidvid reviews it, if it's good to go then this issue will be fixed.
