### ISSUE TITLE
Ballot Page: OP amounts wrong

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#246]
### What was the URL where the error occurred?

https://develop-op-voting.up.railway.app/ballot

### What happened?

The OP amount below the percentage allocation to each project should follow this logic
`RoundAllocation * CategoryAllocation * ProjectAllocation`

In my example, 
`5,000,000 * 10% * 10%` should be 50k OP 

The page shows 333,333 OP 
<img width="1067" alt="Screenshot 2024-09-27 at 10 39 08" src="https://github.com/user-attachments/assets/b733b4db-b121-43bb-baf7-9946813801b3">

### What should have happened instead?

The page should show 50k OP for Tech NERDs

### Steps to Reproduce

1. Go to ballot page
2. See OP amount below percentage allocation

**Comment by JSeiferth** [comment]
This is critical for launch. Would love to check in by mid-day on how we're looking on this

**Comment by JSeiferth** [comment]
Oh I see what's happening, it's returning `RoundAllocation * Project Allocation` instead of `RoundAllocation * CategoryAllocation * ProjectAllocation`

**Comment by vidvidvid** [comment]
@JSeiferth found the bug and fixed it - pls check it https://develop-op-voting.up.railway.app/ballot
feel free to close the issue once you confirm the solution

**Comment by JSeiferth** [comment]
Fixed, thanks @vidvidvid!
