### ISSUE TITLE
Add the round to Retro Funding

### ISSUE THREAD

**Issue by vidvidvid** [grants-stack-frontier/op-rf4-voting-ui#252]
We need to wait for the data to be exposed by the backend.

Reference issue: https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/125

**Comment by meglister** [comment]
Hey @vidvidvid just got a message from Stepan that this is now returned in the `fundingRound` field under the grant object. Can we get this in?

**Comment by vidvidvid** [comment]
@meglister nice, i'll fix that today.
