### ISSUE TITLE
Ballot Page: Number input results in many decimals

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#259]
### What was the URL where the error occurred?

Ballot page

### What happened?

When fixing the last percent inputs to match 100%, the allocation of this project kept on correcting to many decimal points (e.g. 8.499999999 instead of my input of 8.5)

https://github.com/user-attachments/assets/e40001e1-1589-48e4-a2ee-3b9839647b14

### What should have happened instead?

No change what I input

### Steps to Reproduce

1. Go to ballot
2. type in percentage allocation

**Comment by vidvidvid** [comment]
looks like a backend issue. @geovgy can you confirm?

**Comment by geovgy** [comment]
I'm unable to reproduce this issue. Yeah it looks to be an API issue that may have been already patched now.
