### ISSUE TITLE
Error when re-ordering the ballot list

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#274]
### What was the URL where the error occurred?

https://develop-op-voting.up.railway.app/ballot

### What happened?

I tried to change a project from #4 in the list to #1, and the project erroneously was set to #7.

View here at 5:13 https://www.loom.com/share/72baf634107247448dabe43782ea3636?t=313&sid=994638e1-ab40-4e62-9be0-709d6650de7a

### What should have happened instead?

Projects should reorder from high to low.

### Steps to Reproduce

Go to ballot step, turn on Top-Weighted, click in list order, change an order number, note the error when it reloads.

**Comment by vidvidvid** [comment]
this appears to happens only when moving the project to the index 0. it looks like a backend issue
update: it is a backend issue & bugs out also in other scenarios

**Comment by vidvidvid** [comment]
this looks fixed now!
