### ISSUE TITLE
Budget slider should default to low bound (2M OP) when someone first connects

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#275]
### What was the URL where the error occurred?

https://develop-op-voting.up.railway.app/budget

### What happened?

I've created several new wallets to test the app. Landing on the budget step the first time, the slider is set to the high amount (8M OP) when it should set to the far left (2M OP).

Screenshot: 
<img width="1551" alt="Screenshot 2024-09-29 at 4 23 42 PM" src="https://github.com/user-attachments/assets/f94f55b6-c40a-4242-952f-cb7eb96537a9">

### What should have happened instead?

The budget slider should default to the far left (2M OP).

### Steps to Reproduce

Sign in with a new account, view the budget step.

**Comment by vidvidvid** [comment]
@shaunop we got a different request from @JSeiferth

https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/255

**Comment by JSeiferth** [comment]
@shaunop my bad for not flagging. I got some feedback that the slider should default to the 8M side from badgeholders. Let's discuss later!
