### ISSUE TITLE
Unable to advance after scoring project

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#277]
Loom: https://www.loom.com/share/5359314979dc4dd8a2f93a25598293ad?sid=699d4929-ac5d-40d7-a38f-2ae3225c6bf6

To repro:
- Sign in and complete budget allocations
- Land on ballot page, click score projects
- Notice after scoring project, page does not advance to another project
- To advance to another project, the user needs to go back to the ballot and click score projects again

**Comment by meglister** [comment]
Update: got stuck in a loop with the same project -- https://www.loom.com/share/b3b2dcce3f994774a8deb2b5836976eb?sid=611509a3-0790-4629-a81f-6173ec764ae3

**Comment by nitegeist** [comment]
@meglister this issue should be resolved with our PRs #290 & #291. This has been confirmed fixed by @meglister
