### ISSUE TITLE
Make "Voting App" link on retrofunding.io link to Round 5 Voting 

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#289]
### What was the URL where the error occurred?

https://retrofunding.optimism.io/rounds

### What happened?

Clicking on "Voting App" in the "More" menu from topbar links to Round 4 voting.

<img width="1537" alt="Screenshot 2024-09-30 at 1 37 41 PM" src="https://github.com/user-attachments/assets/988b2e7d-664a-4976-af56-35d742cad16b">

### What should have happened instead?

 It should link to Round 5 voting.

### Steps to Reproduce

Go to https://retrofunding.optimism.io/rounds, click "More" in topbar, click "Voting App"

**Comment by stepandel** [comment]
this ticket belongs in [this repo](https://github.com/voteagora/op-atlas)

Closed there ✅

**Comment by nitegeist** [comment]
Thanks for clarifying @stepandel. I'm gonna close this one @shaunop since it's not related to this repo.
