### ISSUE TITLE
Broken links to Testimonials 

### ISSUE THREAD

**Issue by 0xyNaMu** [grants-stack-frontier/op-rf4-voting-ui#297]
### What was the URL where the error occurred?

https://round5.optimism.io/project/0x056236fa3b7b2517f22e884bf78e048e6a29f58f882d5cc186afec84f632664b

### What happened?

When clicking on the Testimonials link, I'm redirected to a 404 page. 
This is because the link structure has changed so it can be created deterministically. Information can be found here: https://www.notion.so/launamu/Links-to-insights-pages-10a77d07048080d5a14ce3f3ae6d0957

### What should have happened instead?

Page should lead to a working website. 

### Steps to Reproduce

1. Go to any project page
2. Click on the link under "Testimonials"

**Comment by stepandel** [comment]
will resolve on the API side. Thank you @0xyNaMu

**Comment by 0xyNaMu** [comment]
Related to this, now that the new links have been updated, they are running over in the UI:
 
![image](https://github.com/user-attachments/assets/7eaf7a2a-d435-4df3-b2ec-4e7d6b0a156f)

**Comment by vidvidvid** [comment]
@0xyNaMu i already noticed and fixed that. will be included in the upcoming pr. thank you for reporting the bugs! :)

![Screenshot 2024-10-03 at 12 45 33](https://github.com/user-attachments/assets/d11b43cb-6e7a-4258-a0b9-028c7f2dd854)
