### ISSUE TITLE
Ballot List: Prevent Drag and Drop when focused on Number Inputs

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#303]
### What was the URL where the error occurred?

https://round5.optimism.io/ballot

### What happened?

When user tries to click and drag either the ranking input or the OP input, the UI grabs the list item for drag-and-drop.

https://github.com/user-attachments/assets/96bf260d-6135-4a6a-9887-615a346b2af0

### What should have happened instead?

The user should be able to operate within the inputs without engaging drag and drop.

### Steps to Reproduce

Go to unlocked ballot, try out the list item inputs.

**Comment by geovgy** [comment]
Fixed and shipped to prod in PR #307
