### ISSUE TITLE
Ballot list: Drag and drop should be disabled in Custom mode

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#304]
### What was the URL where the error occurred?

https://round5.optimism.io/ballot

### What happened?

While in **custom preset** or **impact groups preset**, the buttons for list reordering look disabled, but user can still drag and drop. The UI reacts then shows an error toast.

https://github.com/user-attachments/assets/fd0f4f47-10b1-44bf-b7de-84d38f381b73

### What should have happened instead?

User shouldn't be able pick up a list item to drag it.

### Steps to Reproduce

Go to unlocked ballot, put ballot in custom mode, drag list items.

**Comment by geovgy** [comment]
Fixed and shipped to prod in PR #307
