### ISSUE TITLE
TO DO: Oct 14 1900 UTC close voting

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#311]
To close voting at 1900 UTC on Oct 14

- Disable the submit button on the ballot page
- Change the text in the banner to read "Voting has closed! Results will be announced shortly."

**Comment by geovgy** [comment]
@meglister I added the text but there is already logic for the button to disappear completely when the voting period ends. Which is preferred, disabling or hiding the submit button?

**Comment by meglister** [comment]
fine to have it hidden! thanks
