### ISSUE TITLE
Non-badgeholder view not working as expected

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#318]
### What was the URL where the error occurred?

https://round5.optimism.io/budget

### What happened?

I signed in with a non badgeholder wallet
I am NOT seeing the guest voter banner as I would expect
The agora API is returning 401 errors and not showing count of projects on the ballot page

### What should have happened instead?

Non-badgeholder experience should show demo banner and not result in API errors

### Steps to Reproduce

Screenshot attached
![Screenshot 2024-10-11 at 11 59 38 AM](https://github.com/user-attachments/assets/f4c9651b-b750-4cde-8f7d-83951c67e759)

**Comment by geovgy** [comment]
This issue was occurring, it may have already been solved in PR #319 just now. I'm unable to replicate the bug on my end.

**Comment by meglister** [comment]
Verified that this is fixed
