### ISSUE TITLE
Critical: Budget page not functional

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#320]
### What was the URL where the error occurred?

https://round5.optimism.io/budget

### What happened?

The budget functionality keeps refreshing, blocking users from editing their category budget

https://github.com/user-attachments/assets/12e547c2-50e3-4be6-b9f6-428a7002d9b1

<img width="742" alt="Screenshot 2024-10-12 at 12 38 49" src="https://github.com/user-attachments/assets/81ab9eaf-c474-4b6d-87aa-a202e22d9ec4">

This seems to be an issue on the API, which returns the categories from r5 and R6
<img width="751" alt="Screenshot 2024-10-12 at 12 39 47" src="https://github.com/user-attachments/assets/925c93df-2ae0-47f6-ab31-57d7336ce683">

### What should have happened instead?

This should function like before

### Steps to Reproduce

1. go to [budget page](https://round5.optimism.io/budget)
2. try to edit percentages

### What browser(s) are you seeing the problem on?

Chrome

**Comment by JSeiferth** [comment]
<img width="939" alt="Screenshot 2024-10-12 at 12 49 08" src="https://github.com/user-attachments/assets/a2c65ac9-92cf-4d29-a193-a6a66ad58041">
Also, the RF6 categories seem to be within the payload

**Comment by geovgy** [comment]
I am not experiencing this issue when trying to replicate it so fix on the API side works.
