### ISSUE TITLE
Update the 4th intro carousel image

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#37]
Update the 4th intro carousel image. Should be this image: 

<img width="300" alt="image4" src="https://github.com/user-attachments/assets/7c23eee5-2d81-4e89-8a53-b0c81be028f6">

**Comment by vidvidvid** [comment]
this will be solved in https://github.com/grants-stack-frontier/op-rf4-voting-ui/pull/27
