### ISSUE TITLE
Ballot unlock not working

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#65]
1. The ballot landing page shows me 34 projects to score. When scoring projects, I get shown 4 projects to score. After scoring all and confirm the "unlock ballot" pop-up, I get routed back to the ballot landing page (which is still locked). 
TLDR: Can't get out of scoring projects
<img width="1318" alt="Screenshot 2024-09-17 at 13 32 04" src="https://github.com/user-attachments/assets/c651a417-3e10-4ac8-96c4-c48d00a901fc">

2. Project scores should be editable: I should be able to go back to a project and change my score, as long as I haven't started picking a distribution in my ballot 
<img width="1332" alt="Screenshot 2024-09-17 at 13 35 06" src="https://github.com/user-attachments/assets/4c1d2211-03c7-4fef-ae04-34fef346236d">

**Comment by vidvidvid** [comment]
has to do with discrepancy between projects that need to be evaluated & the projects from one's category. should auto-resolve once we figure this out.

turn the progress bar into a reusable component (ballot & impact score) @geovgy
