### ISSUE TITLE
Repos, links and contracts: Link not clickable

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#66]
Repos, links and contracts should all have clickable links. The name of the link/repo/contract should be clickable

<img width="870" alt="Screenshot 2024-09-17 at 13 37 53" src="https://github.com/user-attachments/assets/410d2f8f-d14f-452f-b792-7c5262b2fc89">

**Comment by shaunop** [comment]
The text of the link or name (if the user added a name for their link, repo, or contract) should be clickable. It should open a new tab. 

Here's a design showing hover states: 
<img width="782" alt="Screenshot 2024-09-17 at 12 47 30 PM" src="https://github.com/user-attachments/assets/3e369338-a3ba-45c3-9dff-b2ccdc0ae686">
