### ISSUE TITLE
Project Detail View title should be Project Name (not Organization Name)

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#74]
It looks like we're using the Organization Name where the Project Name should be. 

1. Just under the Project Avatar should be the Project Name (not the Organization Name)

Screenshots:
<img width="879" alt="Screenshot 2024-09-17 at 1 15 57 PM" src="https://github.com/user-attachments/assets/6bbf3f96-b1f4-495c-a057-978a9c3a01de">
<img width="871" alt="Screenshot 2024-09-17 at 1 13 10 PM" src="https://github.com/user-attachments/assets/217c3cef-8a93-48ca-8026-2b29cf6e0cbf">
<img width="853" alt="Screenshot 2024-09-17 at 1 15 22 PM" src="https://github.com/user-attachments/assets/da3b9ee8-b7d3-4cb0-951b-3b2d320c213e">

Design: 
<img width="1106" alt="Screenshot 2024-09-17 at 1 14 57 PM" src="https://github.com/user-attachments/assets/112241e4-a89d-4623-851e-888b73d447c3">

**Comment by vidvidvid** [comment]
@nitegeist current pr

**Comment by nitegeist** [comment]
It's already using the project name. I think the confusion here came from the `By: Org` section using the project name as well. That was fixed in my most recent PR
