### ISSUE TITLE
Investigate: It shouldn't be possible for a project to have no team members

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#78]
Investigate: It shouldn't be possible for a project to have no team members

Screenshot: 
<img width="851" alt="Screenshot 2024-09-17 at 1 30 17 PM" src="https://github.com/user-attachments/assets/e0bd071d-fb68-4efe-9ed0-61b6f0662dd0">

**Comment by vidvidvid** [comment]
@shaunop a couple projects have an empty array of members, what do we do in that case?
@nitegeist please ask stepan what's happening

**Comment by shaunop** [comment]
This must be an API issue. It's impossible for a project to exist without at least one admin as a contributor (the project creator)

**Comment by stepandel** [comment]
should be resolved in the API
