### ISSUE TITLE
Div.prose vs p-class "paragraph"

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#79]
Project detail view:

It appears there are two versions of paragraph (p) styling. The difference between paragraph and the text I mentioned is noticeable by looking at the line-heights across different sections. Let's please be consistent.

**Comment by vidvidvid** [comment]
@nitegeist remember to ask shaun again after you merge your current pr

**Comment by nitegeist** [comment]
Hey @shaunop feel free to check the app again when you're able to, I'd like to know if my changes have solved this issue.

**Comment by shaunop** [comment]
Looks good!
