### ISSUE TITLE
Unable to save allocation in "Eth Core Contrib" budget

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf4-voting-ui#91]
See overview here: https://www.loom.com/share/abc27411b7ef46caa729352a336d3c41?sid=2133db3e-4362-47ff-b5b7-188876f05c91

Steps to repro:
1. Load https://develop-op-voting.up.railway.app/budget
2. Try to manually type in a number or press plus button in "eth core contributors" line
3. Observe error
4. Observe that other lines do accept manually edits, but the increase/decrease buttons do not work

**Comment by shaunop** [comment]
[From duped issue: ](https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/96)
Here's how the auto-weight functionality is meant to work: 

1. Categories are automatically weighted when added to the ballot - adding up to 100%.
2. Anytime a user edits a category percentage by input, plus, or minus (or clicks the open-lock icon), that category input is “locked”. The icon-button should visually switch to the locked state. That category's percentage can still be adjusted up and down.
3. Non-locked metrics in the list (any metric that hasn't been edited) are then automatically balanced across the remaining percent.
4. When a locked metric is unlocked (by clicking the lock icon), it re-enters the non-locked pool of metrics and is auto-balanced across the remaining percent.

Currently, it doesn't appear to be working like this, or the lag between save times is making it feel broken. [Here's a screen-by-screen from Round 4 Voting that may be helpful.](https://www.figma.com/design/1j0mOMlZWtve4GK5kF0WQU?node-id=2942-123034#837542774)

Here's a screencast: 
[Sep-17-2024 14-32-23.mp4.zip](https://github.com/user-attachments/files/17035215/Sep-17-2024.14-32-23.mp4.zip)

**Comment by vidvidvid** [comment]
The issue is that the user is not connected with the wallet. Should we just disable the buttons in this case or not display the page at all and instead show a connect wallet button?

@shaunop can you please elaborate on 4.? The backend code itself doesn't cause any rebalancing if a category gets unlocked.

**Comment by vidvidvid** [comment]
on `/budget` page i implemented the "disconnected state" component that matches the welcome screen before the user connects the wallet. i suggest we do something similar on every page. @shaunop what do you think?

https://github.com/user-attachments/assets/affc97a3-5c43-4f84-b77b-0b4244f78f83

**Comment by shaunop** [comment]
Hey @vidvidvid, I'm a little lost on this thread. The original issue has to do with the lock-and-auto-balancing feature (for the category percentages). Can you elaborate on that problem? It's unclear to me how the "disconnected state" applies. In my screen record, a wallet was connected.

**Comment by vidvidvid** [comment]
@shaunop please revisit this, it should be working fine. in @meglister 's case it was the problem with not being connected, which is visible from her screen recording.

**Comment by shaunop** [comment]
It's working now, thanks!
